Traceback (most recent call last):
  File "c:\Users\prana\Desktop\newOBGAN\normallearning.py", line 20, in <module>
    wandb.save("./normallearning.py")
  File "C:\Users\prana\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 393, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prana\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 383, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prana\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 1997, in save
    return self._save(
           ^^^^^^^^^^^
  File "C:\Users\prana\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 2056, in _save
    target_path.symlink_to(source_path)
  File "C:\Users\prana\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1198, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\prana\\Desktop\\newOBGAN\\normallearning.py' -> 'C:\\Users\\prana\\Desktop\\newOBGAN\\wandb\\run-20250211_203828-jyobobse\\files\\normallearning.py'
